servers=[
  {
    :hostname => "puppetm01",
    :box => "puppetm01",
    :ram => 512,
    :cpu => 1
  },
  {
    :hostname => "puppetagent01",
    :box => "puppetagent01",
    :ram => 512,
    :cpu => 1
  }
]


Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            end
        end
    end
end