## setting up vb name as centos01

Vagrant.configure('2') do |config|
    config.vm.box = "centos/7"
    config.vm.box_url = "http://files.vagrantup.com/centos7.box"
    config.vm.define "centos01"
    config.vm.provider :virtualbox do |vb|
        vb.name = "centos01"
    end
end